---
- name: Make sure docker is installed and configured
  hosts: all  # cf. the hosts file below for this group of hosts
  become: yes
  tasks:
  - name: Update repositories cache 
    apt:
      update_cache: yes
  - name: Install a list of general utilities
    apt: name={{item}} state=installed
    with_items:
      - git
      - jq
      - ipcalc
  - name: Install a list of packages for docker
    apt: name={{item}} state=installed
    with_items:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python-pip
  - name: Fetch the *Ubuntu* GPG key for the docker repository
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present
  - name: Add the docker repository to apt
    command: bash -c 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(lsb_release -is | tr [:upper:] [:lower:]) $(lsb_release -cs) stable"'
  - name: Update repositories cache (with the docker repo now)
    apt:
      update_cache: yes
  - name: Install docker
    apt: name=docker-ce=17.03.1* state=installed

