- hosts: all
  become: yes
  tasks:
   - name: install Docker Dependencies
     apt:
       name: ['apt-transport-https','software-properties-common','gnupg-agent','curl','ca-certificates']
       state: present
       update_cache: true
    
   - name: Fetch the *Ubuntu* GPG key for the docker repository
     apt_key:
       url: "https://download.docker.com/linux/ubuntu/gpg"
       state: present   

   - name: Add Docker official key
     command: bash -c 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(lsb_release -is | tr [:upper:] [:lower:]) $(lsb_release -cs) stable"'
   
   - name: Update repositories cache (with the docker repo now)
     apt:
       update_cache: yes

   - name: Install Docker
     apt:
       name: docker-ce=17.03.1*
       state: present
   
   - name: add Kubernetes apt-key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present
   
   - name: add Kubernetes' APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

   - name: install kubelet
     apt:
       name: kubelet=1.10.12-00
       state: present
       update_cache: true

   - name: install kubeadm
     apt:
       name: kubeadm=1.10.12-00
       state: present

- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     apt:
       name: kubectl=1.10.12-00
       state: present
       force: yes
